doctrine:
    dbal:
        driver: pdo_pgsql
        dbname: '%env(resolve:POSTGRES_DB)%'
        host: '%env(resolve:POSTGRES_HOST)%'
        port: '%env(resolve:POSTGRES_PORT)%'
        user: '%env(resolve:POSTGRES_USER)%'
        password: '%env(resolve:POSTGRES_PASSWORD)%'
        charset: '%env(resolve:POSTGRES_CHARSET)%'
        server_version: '%env(resolve:POSTGRES_VERSION)%'
        profiling_collect_backtrace: '%kernel.debug%'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
