twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        nav_links: '@App\Framework\Provider\NavProvider'

when@test:
    twig:
        strict_variables: true
