version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: _docker/config/nginx.dockerfile
    volumes:
      - "./:/var/www:delegated"
      - "./_docker/config/nginx/conf.d/:/etc/nginx/conf.d/:delegated"
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - facman-network
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    networks:
      - facman-network
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: _docker/config/app.dockerfile
    volumes:
      - '.:/var/www:delegated'
    networks:
      - facman-network

networks:
  facman-network:
    driver: bridge
      