<?php

namespace App\Tests\Application\Controller;

use App\Application\Company\CompanyFinderException;
use App\Application\Company\CompanyFinderInterface;
use App\Domain\Company\CompanyEntity;
use App\Domain\Company\CompanyRepositoryException;
use App\Domain\Company\CompanyRepositoryInterface;
use App\Tests\Application\ApplicationTestCase;
use LogicException;
use Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException;
use Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException;
use Symfony\Component\Routing\Exception\InvalidParameterException;
use Symfony\Component\Routing\Exception\MissingMandatoryParametersException;
use Symfony\Component\Routing\Exception\RouteNotFoundException;
use TypeError;

/**
 * @internal
 */
final class CompanyControllerTest extends ApplicationTestCase
{
    private CompanyFinderInterface $finder;
    private CompanyRepositoryInterface $repository;

    /**
     * @throws ServiceCircularReferenceException
     * @throws ServiceNotFoundException
     * @throws TypeError
     * @throws LogicException
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        /** @var CompanyFinderInterface $finder */
        $finder = self::getContainer()->get(CompanyFinderInterface::class);
        $this->finder = $finder;

        /** @var CompanyRepositoryInterface $repository */
        $repository = self::getContainer()->get(CompanyRepositoryInterface::class);
        $this->repository = $repository;
    }

    /**
     * @throws InvalidParameterException
     * @throws MissingMandatoryParametersException
     * @throws RouteNotFoundException
     *                                             tag
     */
    public function testIndex(): void
    {
        $crawler = $this->client->request(
            'GET',
            $this->router->generate('company.index')
        );

        self::assertResponseIsSuccessful();
    }

    /**
     * @throws CompanyFinderException
     */
    public function testCreate(): void
    {
        $testPrefix = 'CTC';
        $this->checkForm(
            'company.create',
            [],
            'create_company_form',
            [
                'create_company_form[name]' => 'Create Test Company',
                'create_company_form[prefix]' => $testPrefix,
                'create_company_form[description]' => 'Test Company',
            ]
        );
        self::assertResponseRedirects();

        $company = $this->finder->findByPrefix($testPrefix);
        self::assertEquals($testPrefix, $company->prefix);
    }

    /**
     * @throws CompanyFinderException
     * @throws CompanyRepositoryException
     */
    public function testUpdate(): void
    {
        $id = $this->repository->generateId();
        $originalName = 'Update Test Company';
        $originalDescription = 'a description';
        $company = new CompanyEntity(
            id: $id,
            name: $originalName,
            description: $originalDescription,
            prefix: 'UTC'
        );
        $this->repository->store($company);

        $newName = 'Update Test Company Again';
        $newDescription = 'Changed';

        $this->checkForm(
            'company.update',
            ['id' => $id],
            'update_company_form',
            [
                'update_company_form[name]' => $newName,
                'update_company_form[description]' => $newDescription,
            ],
            [
                'update_company_form[name]' => $originalName,
                'update_company_form[description]' => $originalDescription,
            ]
        );
        self::assertResponseRedirects();

        $company = $this->finder->findById($id);
        self::assertEquals($newName, $company->name);
        self::assertEquals($newDescription, $company->description);
    }
}
