<?php

namespace App\Tests\Application\Controller;

use App\Application\JobStatus\JobStatusFinderInterface;
use App\Application\JobStatus\JobStatusModel;
use App\Domain\JobStatus\JobStatusEntity;
use App\Domain\JobStatus\JobStatusRepositoryInterface;
use App\Tests\Application\ApplicationTestCase;
use PHPUnit\Framework\Attributes\Test;
use Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException;
use Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException;
use Symfony\Component\Routing\Exception\InvalidParameterException;
use Symfony\Component\Routing\Exception\MissingMandatoryParametersException;
use Symfony\Component\Routing\Exception\RouteNotFoundException;
use TypeError;

/**
 * @internal
 */
final class JobStatusControllerTest extends ApplicationTestCase
{
    private JobStatusFinderInterface $finder;
    private JobStatusRepositoryInterface $repository;

    /**
     * @throws InvalidParameterException
     * @throws MissingMandatoryParametersException
     * @throws RouteNotFoundException
     * @throws ServiceCircularReferenceException
     * @throws ServiceNotFoundException
     * @throws TypeError
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        /** @var JobStatusFinderInterface $finder */
        $finder = self::getContainer()->get(JobStatusFinderInterface::class);
        $this->finder = $finder;

        /** @var JobStatusRepositoryInterface $repository */
        $repository = self::getContainer()->get(JobStatusRepositoryInterface::class);
        $this->repository = $repository;
    }

    /**
     * @throws InvalidParameterException
     * @throws MissingMandatoryParametersException
     * @throws RouteNotFoundException
     *                                             tag
     */
    public function testIndex(): void
    {
        $crawler = $this->client->request(
            'GET',
            $this->router->generate('job-status.index')
        );

        self::assertResponseIsSuccessful();
    }

    #[Test]
    public function testCreate(): void
    {
        $this->checkForm(
            'job-status.create',
            [],
            'create_job_status_form',
            [
                'create_job_status_form[name]' => self::class,
                'create_job_status_form[description]' => 'Test JobStatus',
                'create_job_status_form[colour]' => '#FF0000',
            ]
        );
        self::assertResponseRedirects();

        $allStatuses = $this->finder->all();
        self::assertContains(
            self::class,
            array_map(
                fn (JobStatusModel $jsm) => $jsm->name,
                $allStatuses
            )
        );
    }

    public function testUpdate(): void
    {
        $id = $this->repository->generateId();
        $originalName = 'Update Test JobStatus';
        $originalDescription = 'a description';
        $job_status = new JobStatusEntity(
            id: $id,
            name: $originalName,
            description: $originalDescription,
            colour: '#BADA55'
        );
        $this->repository->store($job_status);

        $newName = 'Update Test JobStatus Again';
        $newDescription = 'Changed';

        $this->checkForm(
            'job-status.update',
            ['id' => $id],
            'update_job_status_form',
            [
                'update_job_status_form[name]' => $newName,
                'update_job_status_form[description]' => $newDescription,
            ],
            [
                'update_job_status_form[name]' => $originalName,
                'update_job_status_form[description]' => $originalDescription,
            ]
        );
        self::assertResponseRedirects();

        $job_status = $this->finder->findById($id);
        self::assertEquals($newName, $job_status->name);
        self::assertEquals($newDescription, $job_status->description);
    }
}
