<?php

namespace App\Tests\Application\Controller;

use App\Application\JobType\JobTypeFinderInterface;
use App\Application\JobType\JobTypeModel;
use App\Domain\JobType\JobTypeEntity;
use App\Domain\JobType\JobTypeRepositoryInterface;
use App\Tests\Application\ApplicationTestCase;
use PHPUnit\Framework\Attributes\Test;

/**
 * @internal
 */
final class JobTypeControllerTest extends ApplicationTestCase
{
    private JobTypeFinderInterface $finder;
    private JobTypeRepositoryInterface $repository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->finder = $this->getContainer()->get(JobTypeFinderInterface::class);
        $this->repository = $this->getContainer()->get(JobTypeRepositoryInterface::class);
    }

    #[Test]
    public function testIndex(): void
    {
        $crawler = $this->client->request(
            'GET',
            $this->router->generate('job-type.index')
        );

        $this->assertResponseIsSuccessful();
    }

    #[Test]
    public function testCreate(): void
    {
        $this->checkForm(
            $this->router->generate('job-type.create'),
            'create_job_type_form',
            [
                'create_job_type_form[name]' => self::class,
                'create_job_type_form[description]' => 'Test JobType',
                'create_job_type_form[colour]' => '#FF0000',
            ]
        );
        $this->assertResponseRedirects();

        $allStatuses = $this->finder->all();
        $this->assertContains(
            self::class,
            array_map(
                fn (JobTypeModel $jsm) => $jsm->name,
                $allStatuses
            )
        );
    }

    public function testUpdate(): void
    {
        $id = $this->repository->generateId();
        $originalName = 'Update Test JobType';
        $originalDescription = 'a description';
        $job_type = new JobTypeEntity(
            id: $id,
            name: $originalName,
            description: $originalDescription,
            colour: '#BADA55'
        );
        $this->repository->store($job_type);

        $newName = 'Update Test JobType Again';
        $newDescription = 'Changed';

        $this->checkForm(
            $this->router->generate('job-type.update', ['id' => $id]),
            'update_job_type_form',
            [
                'update_job_type_form[name]' => $newName,
                'update_job_type_form[description]' => $newDescription,
            ],
            [
                'update_job_type_form[name]' => $originalName,
                'update_job_type_form[description]' => $originalDescription,
            ]
        );
        $this->assertResponseRedirects();

        $job_type = $this->finder->findById($id);
        $this->assertEquals($newName, $job_type->name);
        $this->assertEquals($newDescription, $job_type->description);
    }
}
