<?php

namespace App\Tests\Application\Controller;

use App\Application\Company\CompanyFinderInterface;
use App\Application\Site\SiteFinderInterface;
use App\Domain\Company\CompanyEntity;
use App\Domain\Company\CompanyRepositoryInterface;
use App\Domain\Company\ValueObject\CompanyId;
use App\Domain\Site\SiteEntity;
use App\Domain\Site\SiteRepositoryInterface;
use App\Tests\Application\ApplicationTestCase;
use PHPUnit\Framework\Attributes\Test;

/**
 * @internal
 */
final class SiteControllerTest extends ApplicationTestCase
{
    private const COMPANY_ID = '0190e1b8-e7dc-7d6a-9f13-d4360dd2f2d1';
    private SiteFinderInterface $finder;
    private SiteRepositoryInterface $repository;

    private CompanyFinderInterface $companyFinder;

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub

        /** @var CompanyRepositoryInterface $companyRepository */
        $companyRepository = self::getContainer()->get(CompanyRepositoryInterface::class);
        $company = new CompanyEntity(
            id: CompanyId::fromString(self::COMPANY_ID),
            name: 'Test Company',
            description: 'Test Company',
            prefix: self::class.time()
        );
        $companyRepository->store($company);
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->finder = $this->getContainer()->get(SiteFinderInterface::class);
        $this->repository = $this->getContainer()->get(SiteRepositoryInterface::class);
        $this->companyFinder = $this->getContainer()->get(CompanyFinderInterface::class);
    }

    #[Test]
    public function testIndex(): void
    {
        $crawler = $this->client->request(
            'GET',
            $this->router->generate('site.index')
        );

        $this->assertResponseIsSuccessful();
    }

    #[Test]
    public function testCreate(): void
    {
        $testName = 'Create Test Site';
        $this->checkForm(
            $this->router->generate('site.create'),
            'create_site_form',
            [
                'create_site_form[name]' => $testName,
                'create_site_form[company]' => (string) self::COMPANY_ID,
                'create_site_form[description]' => 'Test Site',
                'create_site_form[address][line1]' => 'Somewhere over the rainbow',
            ]
        );
        $this->assertResponseRedirects();

        $sites = $this->finder->allForCompany(CompanyId::fromString(self::COMPANY_ID));
        $site = array_shift($sites);
        $this->assertEquals($testName, $site->name);
    }

    public function testUpdate(): void
    {
        $id = $this->repository->generateId();
        $originalName = 'Update Test Site';
        $originalDescription = 'a description';
        $site = new SiteEntity(
            id: $id,
            name: $originalName,
            description: $originalDescription,
            companyId: CompanyId::fromString(self::COMPANY_ID)
        );
        $this->repository->store($site);

        $newName = 'Update Test Site Again';
        $newDescription = 'Changed';

        $this->checkForm(
            $this->router->generate('site.update', ['id' => $id]),
            'update_site_form',
            [
                'update_site_form[name]' => $newName,
                'update_site_form[description]' => $newDescription,
            ],
            [
                'update_site_form[name]' => $originalName,
                'update_site_form[description]' => $originalDescription,
            ]
        );
        $this->assertResponseRedirects();

        $site = $this->finder->findById($id);
        $this->assertEquals($newName, $site->name);
        $this->assertEquals($newDescription, $site->description);
    }
}
