<?php

namespace App\Tests\Application\Controller;

use App\Application\Site\SiteFinderException;
use App\Application\Site\SiteFinderInterface;
use App\Domain\Company\CompanyRepositoryException;
use App\Domain\Company\ValueObject\CompanyId;
use App\Domain\Site\SiteEntity;
use App\Domain\Site\SiteRepositoryException;
use App\Domain\Site\SiteRepositoryInterface;
use App\Tests\Application\ApplicationTestCase;
use PHPUnit\Framework\Attributes\Test;

/**
 * @internal
 */
final class SiteControllerTest extends ApplicationTestCase
{
    private SiteFinderInterface $finder;
    private SiteRepositoryInterface $repository;

    private static CompanyId $companyId;

    /**
     * @throws CompanyRepositoryException
     */
    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub

        self::$companyId = self::createCompany();
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->finder = $this->getContainer()->get(SiteFinderInterface::class);
        $this->repository = $this->getContainer()->get(SiteRepositoryInterface::class);
    }

    #[Test]
    public function testIndex(): void
    {
        $this->client->request(
            'GET',
            $this->router->generate('site.index')
        );

        $this->assertResponseIsSuccessful();
    }

    /**
     * @throws SiteFinderException
     */
    #[Test]
    public function testCreate(): void
    {
        $testName = 'Create Test Site';
        $this->checkForm(
            $this->router->generate('site.create'),
            'create_site_form',
            [
                'create_site_form[name]' => $testName,
                'create_site_form[company]' => (string) self::$companyId,
                'create_site_form[description]' => 'Test Site',
                'create_site_form[address][line1]' => 'Somewhere over the rainbow',
            ]
        );
        $this->assertResponseRedirects();

        $sites = $this->finder->allForCompany(CompanyId::fromString(self::$companyId));
        $site = array_shift($sites);
        $this->assertEquals($testName, $site->name);
    }

    /**
     * @throws SiteFinderException
     * @throws SiteRepositoryException
     */
    public function testUpdate(): void
    {
        $id = $this->repository->generateId();
        $originalName = 'Update Test Site';
        $originalDescription = 'a description';
        $site = new SiteEntity(
            id: $id,
            name: $originalName,
            description: $originalDescription,
            companyId: CompanyId::fromString(self::$companyId)
        );
        $this->repository->store($site);

        $newName = 'Update Test Site Again';
        $newDescription = 'Changed';

        $this->checkForm(
            $this->router->generate('site.update', ['id' => $id]),
            'update_site_form',
            [
                'update_site_form[name]' => $newName,
                'update_site_form[description]' => $newDescription,
            ],
            [
                'update_site_form[name]' => $originalName,
                'update_site_form[description]' => $originalDescription,
            ]
        );
        $this->assertResponseRedirects();

        $site = $this->finder->findById($id);
        $this->assertEquals($newName, $site->name);
        $this->assertEquals($newDescription, $site->description);
    }
}
