<?php

namespace App\Tests\Application;

use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

/**
 * @internal
 *
 * @coversNothing
 */
class ApplicationTestCase extends WebTestCase
{
    protected KernelBrowser $client;
    protected UrlGeneratorInterface $router;

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        self::bootKernel();
    }

    protected function setUp(): void
    {
        $client = $this->getContainer()->get('test.client');
        $this->client = self::getClient($client);

        /** @var UrlGeneratorInterface $router */
        $router = $this->getContainer()->get(UrlGeneratorInterface::class);
        $this->router = $router;
    }

    /**
     * @param string               $route    The generated route for the form
     * @param string               $formName The name of the form
     * @param array<string, mixed> $newData  The data to add to the form
     * @param array<string, mixed> $oldData  The data that should be present in the form already
     */
    protected function checkForm(
        string $route,
        string $formName,
        array $newData,
        array $oldData = []
    ): void {
        $response = $this->client->request('GET', $route);
        $this->assertResponseIsSuccessful();

        $form = $response->filterXPath("//form[@name='{$formName}']")->form();
        $originalFormValues = $form->getValues();
        foreach ($oldData as $oldDataKey => $oldDataValue) {
            $this->assertEquals($oldDataValue, $originalFormValues[$oldDataKey]);
        }
        $form->setValues($newData);
        $this->client->submit($form);
    }
}
