<?php

declare(strict_types=1);

namespace App\Framework\Form\Floor;

use Symfony\Component\Form\FormBuilderInterface;

class UpdateFloorFormType extends CreateFloorFormType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder->remove('building');
    }
}
