name: Auto-merge Dependabot PRs
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    name: Auto-merge dependabot where appropriate
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Leave a comment with the metadata extracted
        run: gh pr comment "$PR_URL" --body "Type is ${{steps.metadata.outputs.update-type}}"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge for Dependabot PRs
        if: |
          endsWith(steps.metadata.outputs.update-type, 'semver-patch') ||
          endsWith(steps.metadata.outputs.update-type, 'semver-minor')
        run: |
          gh pr comment "$PR_URL" --body "Merging" && \
          gh pr review --approve "$PR_URL" && \
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
