name: Testing

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Cache Composer
              id: cache-composer
              uses: actions/cache@v3
              with:
                path: vendor
                key: ${{ hashFiles('composer.lock') }}
            - name: Cache NPM
              id: cache-npm
              uses: actions/cache@v3
              with:
                path: node_modules
                key: ${{ hashFiles('package-lock.json') }}
            - name: Install
              run: ./bin/docker/util/install
            - name: Start
              run: ./bin/docker/util/start
            - name: ECS
              run: ./bin/docker/app/composer cs-fix
              if: always()
            - name: Stan
              run: ./bin/docker/app/composer stan
              if: always()
            - name: PHPUnit With Coverage
              run: ./bin/docker/app/phpunit-with-coverage
              if: always()
